<?php

namespace Database\Seeders;

use Database\Seeders\Concerns\SeedsServiceContent;
use Illuminate\Database\Seeder;

class CloudSecurityContentSeeder extends Seeder
{
    use SeedsServiceContent;

    public function run(): void
    {
        $capability = $this->seedCapability([
            'slug' => 'cloud-security',
            'category' => 'cloud_security',
            'title' => 'Cloud & Cyber Security',
            'short_description' => 'Cloud consulting, migration, cybersecurity, and managed protection services for secure, scalable operations.',
            'icon' => 'capabilities/cloud-security-3ao6oank.png',
            'sort_order' => 4,
        ]);

        foreach ($this->services() as $service) {
            $this->seedService($capability, array_merge($service, ['category' => 'cloud_security']));
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function services(): array
    {
        return [
            [
                'slug' => 'aws-consulting',
                'title' => 'AWS Consulting',
                'icon' => 'services/Cloud-Computing.webp',
                'banner_image' => 'services/Cloud-Computing.webp',
                'sort_order' => 1,
                'short_description' => 'AWS consulting for architecture, migration, cost control, security, DevOps, monitoring, and managed cloud operations.',
                'seo_title' => 'AWS Consulting Services in Navi Mumbai | Tectignis',
                'seo_description' => 'AWS consulting services in Navi Mumbai for cloud architecture, migration, cost optimization, security, DevOps, monitoring, and managed AWS support.',
                'heading' => 'AWS Consulting for Secure, Scalable Cloud Growth',
                'intro' => 'Build and run AWS environments that are reliable, cost-aware, and ready for business-critical workloads. We help you plan, migrate, secure, optimize, and manage AWS with practical engineering support.',
                'bullets' => [
                    'Well-structured AWS architecture for apps, data, and teams',
                    'Migration planning with security and rollback controls',
                    'Cost, performance, backup, and monitoring improvements',
                ],
                'sub_services' => [
                    ['title' => 'AWS Architecture Review', 'description' => 'Assess workloads, accounts, networking, storage, databases, and resilience requirements.'],
                    ['title' => 'AWS Landing Zone Setup', 'description' => 'Create organized accounts, IAM, VPCs, logging, backups, and governance foundations.'],
                    ['title' => 'Application Migration', 'description' => 'Move applications, servers, databases, and files to AWS with planned cutover steps.'],
                    ['title' => 'AWS Cost Optimization', 'description' => 'Review sizing, storage, reserved capacity, idle resources, and monthly spend patterns.'],
                    ['title' => 'Cloud Security Hardening', 'description' => 'Tighten IAM, encryption, network access, monitoring, secrets, and backup controls.'],
                    ['title' => 'Managed AWS Operations', 'description' => 'Handle monitoring, patching, backups, incidents, and ongoing cloud improvements.'],
                ],
                'why_points' => [
                    'AWS planning guided by reliability, security, cost, and maintainability',
                    'Migration roadmaps that reduce downtime and protect existing data',
                    'Practical governance for teams, accounts, access, and production changes',
                    'Cloud bills reviewed with clear savings recommendations',
                    'Ongoing support for workloads after the first launch or migration',
                ],
                'faqs' => [
                    ['question' => 'Can you audit our existing AWS account?', 'answer' => 'Yes. We can review architecture, cost, IAM, networking, security, backups, monitoring, and operational risks.'],
                    ['question' => 'Can you migrate our current servers to AWS?', 'answer' => 'Yes. We plan workload movement, data transfer, testing, cutover, and fallback steps before production migration.'],
                    ['question' => 'Can you reduce AWS bills?', 'answer' => 'Often, yes. We review idle resources, storage classes, instance sizing, reservations, scaling, and architecture choices.'],
                    ['question' => 'Do you manage AWS after setup?', 'answer' => 'Yes. We can provide monitoring, patching, backup checks, incident support, and continuous optimization.'],
                ],
                'tech_stacks' => ['AWS', 'Docker', 'Kubernetes', 'Linux', 'MySQL', 'PostgreSQL'],
                'industries' => ['Corporate Offices', 'E-commerce', 'Finance & Banking', 'Healthcare', 'Startups'],
                'cta_heading' => 'Ready to Build a Stronger AWS Environment?',
            ],
            [
                'slug' => 'microsoft-azure-consulting',
                'title' => 'Microsoft Azure Consulting',
                'icon' => 'services/microsoft-azure-consulting.png',
                'banner_image' => 'services/microsoft-azure-consulting.png',
                'sort_order' => 2,
                'short_description' => 'Microsoft Azure consulting for cloud migration, identity, security, app hosting, DevOps, and managed Azure operations.',
                'seo_title' => 'Microsoft Azure Consulting in Navi Mumbai | Tectignis',
                'seo_description' => 'Microsoft Azure consulting in Navi Mumbai for migration, cloud architecture, Entra ID, security, DevOps, app hosting, and managed Azure support.',
                'heading' => 'Microsoft Azure Consulting for Modern Business Infrastructure',
                'intro' => 'Use Azure to connect cloud infrastructure, Microsoft identity, business applications, and secure operations. We help companies design, migrate, and manage Azure environments with a clear focus on reliability and control.',
                'bullets' => [
                    'Azure architecture for apps, data, identity, and networks',
                    'Migration support for Windows, Linux, and database workloads',
                    'Security, backup, monitoring, and cost governance',
                ],
                'sub_services' => [
                    ['title' => 'Azure Environment Design', 'description' => 'Plan subscriptions, resource groups, networking, compute, storage, and security baselines.'],
                    ['title' => 'Azure Migration', 'description' => 'Move servers, databases, applications, and files to Azure with tested migration steps.'],
                    ['title' => 'Identity and Access', 'description' => 'Configure Entra ID, conditional access, MFA, roles, and secure administrator workflows.'],
                    ['title' => 'Azure App Hosting', 'description' => 'Deploy web apps, APIs, databases, containers, and background services on Azure.'],
                    ['title' => 'Azure DevOps Setup', 'description' => 'Create CI/CD pipelines, repositories, release flows, and deployment controls.'],
                    ['title' => 'Managed Azure Support', 'description' => 'Monitor workloads, backups, alerts, patches, incidents, and monthly optimization.'],
                ],
                'why_points' => [
                    'Strong fit for organizations already using Microsoft 365 or Windows workloads',
                    'Identity-first cloud planning with MFA, access policies, and role separation',
                    'Migration playbooks that protect uptime, data, and user access',
                    'Cost and license guidance for predictable Azure operations',
                    'Hands-on support for both application teams and IT administrators',
                ],
                'faqs' => [
                    ['question' => 'Can you connect Azure with Microsoft 365 identity?', 'answer' => 'Yes. We can configure Entra ID, MFA, conditional access, roles, and secure sign-in flows.'],
                    ['question' => 'Can Windows Server workloads move to Azure?', 'answer' => 'Yes. We can migrate Windows and Linux servers, databases, and applications after readiness assessment.'],
                    ['question' => 'Can you set up Azure DevOps pipelines?', 'answer' => 'Yes. We build CI/CD pipelines, release environments, approval gates, and deployment workflows.'],
                    ['question' => 'Do you provide Azure monitoring?', 'answer' => 'Yes. We can configure alerts, logs, backup checks, uptime monitoring, and operational reports.'],
                ],
                'tech_stacks' => ['Azure', 'Microsoft', 'Docker', 'Kubernetes', 'Linux', '.NET'],
                'industries' => ['Corporate Offices', 'Finance & Banking', 'Healthcare', 'Manufacturing', 'Education'],
                'cta_heading' => 'Ready to Move Smarter With Azure?',
            ],
            [
                'slug' => 'google-cloud-services',
                'title' => 'Google Cloud Services',
                'icon' => 'services/google-cloud-services.png',
                'banner_image' => 'services/google-cloud-services.png',
                'sort_order' => 3,
                'short_description' => 'Google Cloud services for app hosting, data platforms, analytics, AI workloads, containers, migration, and managed support.',
                'seo_title' => 'Google Cloud Services in Navi Mumbai | Tectignis',
                'seo_description' => 'Google Cloud services in Navi Mumbai for cloud architecture, migration, BigQuery, app hosting, containers, AI workloads, monitoring, and managed GCP support.',
                'heading' => 'Google Cloud Services for Data-Driven Cloud Platforms',
                'intro' => 'Use Google Cloud to host applications, analyze data, and build intelligent services with a secure foundation. We design and manage GCP environments for teams that need speed, analytics, and scalable infrastructure.',
                'bullets' => [
                    'GCP architecture for apps, data, APIs, and AI workloads',
                    'BigQuery, analytics, container, and serverless planning',
                    'Secure migration and managed cloud operations',
                ],
                'sub_services' => [
                    ['title' => 'GCP Architecture Planning', 'description' => 'Design projects, networks, IAM, compute, storage, databases, and security boundaries.'],
                    ['title' => 'Cloud Migration to GCP', 'description' => 'Move selected applications, data stores, APIs, and workloads with a clear migration plan.'],
                    ['title' => 'Data and Analytics Platforms', 'description' => 'Build data pipelines, warehouses, dashboards, and reporting foundations with BigQuery.'],
                    ['title' => 'Container and Serverless Hosting', 'description' => 'Deploy services using GKE, Cloud Run, APIs, and managed infrastructure patterns.'],
                    ['title' => 'AI and ML Enablement', 'description' => 'Prepare infrastructure and data flows for machine learning and AI-enabled features.'],
                    ['title' => 'Managed GCP Operations', 'description' => 'Support monitoring, backups, cost reviews, security checks, and platform improvements.'],
                ],
                'why_points' => [
                    'Strong planning for analytics-heavy, API-driven, and AI-ready workloads',
                    'Secure IAM and project structure that keeps teams and environments separated',
                    'Cloud Run and GKE options for scalable application deployment',
                    'Data architecture support for reporting, dashboards, and ML use cases',
                    'Post-launch monitoring and optimization for cost, speed, and reliability',
                ],
                'faqs' => [
                    ['question' => 'Is Google Cloud suitable for analytics projects?', 'answer' => 'Yes. GCP is strong for data pipelines, BigQuery, dashboards, and analytics workloads.'],
                    ['question' => 'Can you migrate only selected workloads?', 'answer' => 'Yes. We can move specific applications, databases, APIs, or reporting systems instead of forcing a full migration.'],
                    ['question' => 'Can GCP support AI and ML projects?', 'answer' => 'Yes. We can prepare infrastructure, storage, data pipelines, and deployment paths for AI and ML workloads.'],
                    ['question' => 'Do you manage Google Cloud costs?', 'answer' => 'Yes. We review resource usage, storage, compute, scaling, and architecture to help control spend.'],
                ],
                'tech_stacks' => ['Google Cloud', 'Docker', 'Kubernetes', 'Python', 'PostgreSQL', 'TensorFlow'],
                'industries' => ['E-commerce', 'Logistics', 'Finance & Banking', 'Retail', 'Startups'],
                'cta_heading' => 'Ready to Build on Google Cloud?',
            ],
            [
                'slug' => 'cloud-migration-services',
                'title' => 'Cloud Migration Services',
                'icon' => 'services/cloud-migration-services.png',
                'banner_image' => 'services/cloud-migration-services.png',
                'sort_order' => 4,
                'short_description' => 'Cloud migration services for servers, applications, databases, files, security, testing, cutover, and post-migration support.',
                'seo_title' => 'Cloud Migration Services in Navi Mumbai | Tectignis',
                'seo_description' => 'Cloud migration services in Navi Mumbai for applications, servers, databases, files, security, testing, cutover planning, and post-migration support.',
                'heading' => 'Cloud Migration Services With Less Risk and More Control',
                'intro' => 'Move from ageing infrastructure to the cloud with a plan your team can understand. We assess workloads, prepare environments, migrate data, test carefully, and stabilize systems after go-live.',
                'bullets' => [
                    'Migration roadmap for apps, servers, databases, and files',
                    'Testing, cutover, rollback, and data validation planning',
                    'Security, backup, monitoring, and cost setup after migration',
                ],
                'sub_services' => [
                    ['title' => 'Migration Readiness Assessment', 'description' => 'Review current servers, applications, dependencies, data, licenses, and business priorities.'],
                    ['title' => 'Cloud Roadmap', 'description' => 'Plan target architecture, migration waves, owners, timelines, risks, and cutover windows.'],
                    ['title' => 'Server and Application Migration', 'description' => 'Move workloads to AWS, Azure, Google Cloud, or hybrid environments with testing.'],
                    ['title' => 'Database Migration', 'description' => 'Transfer databases with backups, consistency checks, performance tests, and rollback planning.'],
                    ['title' => 'Security and Backup Setup', 'description' => 'Configure access, firewalls, encryption, backup schedules, and monitoring baselines.'],
                    ['title' => 'Post-Migration Stabilization', 'description' => 'Tune performance, resolve issues, optimize spend, and support users after launch.'],
                ],
                'why_points' => [
                    'Migration planning based on application dependencies and business downtime tolerance',
                    'Clear testing and rollback steps before production cutover',
                    'Cloud provider selection guided by workload, budget, compliance, and team skills',
                    'Security and backup included as migration fundamentals, not afterthoughts',
                    'Support after go-live to handle tuning, access, performance, and user issues',
                ],
                'faqs' => [
                    ['question' => 'How do you reduce downtime during migration?', 'answer' => 'We plan migration waves, test restores, validate data, schedule cutovers carefully, and prepare rollback options.'],
                    ['question' => 'Can you migrate databases safely?', 'answer' => 'Yes. We use backups, migration tools, integrity checks, test runs, and cutover planning for database moves.'],
                    ['question' => 'Can we use a hybrid setup?', 'answer' => 'Yes. We can connect on-premise systems with cloud workloads when a phased or hybrid model makes more sense.'],
                    ['question' => 'Do you support users after migration?', 'answer' => 'Yes. We provide stabilization support for access, performance, monitoring, backups, and operational issues after go-live.'],
                ],
                'tech_stacks' => ['AWS', 'Azure', 'Google Cloud', 'Docker', 'Linux', 'VMware'],
                'industries' => ['Corporate Offices', 'Manufacturing', 'Healthcare', 'Finance & Banking', 'E-commerce'],
                'cta_heading' => 'Ready to Move to the Cloud With Confidence?',
            ],
            [
                'slug' => 'cyber-security-consulting',
                'title' => 'Cyber Security Consulting',
                'icon' => 'services/cyber-security-consulting.png',
                'banner_image' => 'services/cyber-security-consulting.png',
                'sort_order' => 5,
                'short_description' => 'Cyber security consulting for risk assessment, policies, controls, awareness, endpoint protection, compliance, and incident readiness.',
                'seo_title' => 'Cyber Security Consulting in Navi Mumbai | Tectignis',
                'seo_description' => 'Cyber security consulting in Navi Mumbai for risk assessment, security strategy, policies, controls, awareness, compliance, and incident readiness.',
                'heading' => 'Cyber Security Consulting That Turns Risk Into Action',
                'intro' => 'Protect your business by understanding where exposure exists and what to fix first. We provide security consulting that translates technical risk into practical controls, policies, and improvement plans.',
                'bullets' => [
                    'Risk assessment across users, devices, networks, cloud, and apps',
                    'Security policies, controls, and remediation roadmap',
                    'Awareness, compliance, and incident readiness support',
                ],
                'sub_services' => [
                    ['title' => 'Security Risk Assessment', 'description' => 'Review assets, access, network exposure, endpoints, cloud settings, and process gaps.'],
                    ['title' => 'Security Strategy', 'description' => 'Create a prioritized roadmap for controls, tools, policies, monitoring, and governance.'],
                    ['title' => 'Policy and SOP Development', 'description' => 'Prepare practical policies for passwords, access, devices, backups, data, and incidents.'],
                    ['title' => 'Endpoint and Network Review', 'description' => 'Assess antivirus, patching, firewall rules, segmentation, VPN, and device security.'],
                    ['title' => 'Compliance Readiness', 'description' => 'Support audit preparation for frameworks, client requirements, and internal governance.'],
                    ['title' => 'Incident Response Planning', 'description' => 'Define escalation, containment, communication, recovery, and evidence handling steps.'],
                ],
                'why_points' => [
                    'Security advice shaped for business risk, not only technical checklists',
                    'Prioritized remediation so urgent gaps are fixed before lower-impact items',
                    'Policy and awareness support that staff can understand and follow',
                    'Balanced recommendations across people, process, and technology controls',
                    'Ongoing guidance for audits, client questionnaires, and security maturity',
                ],
                'faqs' => [
                    ['question' => 'Can you assess our current security posture?', 'answer' => 'Yes. We review users, systems, networks, cloud, endpoints, backups, policies, and operational practices.'],
                    ['question' => 'Do you create security policies?', 'answer' => 'Yes. We prepare practical policies and SOPs for access, devices, backups, incidents, passwords, and data handling.'],
                    ['question' => 'Can you help with client security questionnaires?', 'answer' => 'Yes. We can review requirements, identify evidence, close gaps, and support responses.'],
                    ['question' => 'Is consulting useful for small businesses?', 'answer' => 'Yes. Smaller teams often benefit from prioritized controls that reduce real risk without unnecessary tool spending.'],
                ],
                'tech_stacks' => ['Fortinet', 'Palo Alto', 'Cisco', 'Microsoft', 'Linux', 'AWS'],
                'industries' => ['Corporate Offices', 'Finance & Banking', 'Healthcare', 'Manufacturing', 'Education'],
                'cta_heading' => 'Ready to Strengthen Your Cyber Security Posture?',
            ],
            [
                'slug' => 'vapt-services',
                'title' => 'VAPT Services',
                'icon' => 'services/vapt-services.png',
                'banner_image' => 'services/vapt-services.png',
                'sort_order' => 6,
                'short_description' => 'VAPT services for web apps, mobile apps, APIs, networks, cloud configurations, reports, remediation guidance, and retesting.',
                'seo_title' => 'VAPT Services in Navi Mumbai | Tectignis',
                'seo_description' => 'VAPT services in Navi Mumbai for web applications, mobile apps, APIs, networks, cloud, vulnerability reports, remediation guidance, and retesting.',
                'heading' => 'VAPT Services That Find Weaknesses Before Attackers Do',
                'intro' => 'Identify exploitable vulnerabilities across applications, APIs, networks, and cloud environments. We deliver clear testing reports, risk ratings, remediation guidance, and retesting support for verified closure.',
                'bullets' => [
                    'Web, mobile, API, network, and cloud security testing',
                    'Clear risk ratings with evidence and remediation steps',
                    'Retesting support after fixes are applied',
                ],
                'sub_services' => [
                    ['title' => 'Web Application VAPT', 'description' => 'Test authentication, authorization, input handling, sessions, uploads, and business logic.'],
                    ['title' => 'API Security Testing', 'description' => 'Review endpoints, tokens, permissions, rate limits, validation, and data exposure risks.'],
                    ['title' => 'Mobile App Testing', 'description' => 'Assess Android and iOS apps for insecure storage, APIs, sessions, and reverse engineering risks.'],
                    ['title' => 'Network VAPT', 'description' => 'Scan and test internal or external network services, ports, devices, and misconfigurations.'],
                    ['title' => 'Cloud Configuration Review', 'description' => 'Check storage, IAM, network rules, exposed services, logging, and backup settings.'],
                    ['title' => 'Reports and Retesting', 'description' => 'Provide evidence, severity, fixes, executive summary, and validation after remediation.'],
                ],
                'why_points' => [
                    'Testing scope matched to your applications, APIs, infrastructure, and compliance needs',
                    'Actionable reports that developers and IT teams can fix from',
                    'Business risk context added to technical severity ratings',
                    'Retesting to confirm issues are resolved before closure',
                    'Confidential handling of findings, credentials, screenshots, and evidence',
                ],
                'faqs' => [
                    ['question' => 'What does VAPT include?', 'answer' => 'Scope can include vulnerability scanning, manual testing, exploitation checks, evidence, reports, remediation guidance, and retesting.'],
                    ['question' => 'Can you test APIs separately?', 'answer' => 'Yes. API VAPT can cover authentication, authorization, validation, rate limits, data exposure, and endpoint behavior.'],
                    ['question' => 'Do you provide a report for audits?', 'answer' => 'Yes. We provide executive and technical findings, severity, evidence, remediation steps, and retest status.'],
                    ['question' => 'Can developers discuss findings with you?', 'answer' => 'Yes. We can walk through findings with technical teams so fixes are understood and applied correctly.'],
                ],
                'tech_stacks' => ['Linux', 'Docker', 'AWS', 'Azure', 'Google Cloud', 'Fortinet'],
                'industries' => ['Finance & Banking', 'Healthcare', 'E-commerce', 'Corporate Offices', 'Government'],
                'cta_heading' => 'Ready to Validate Your Security Before Launch?',
            ],
            [
                'slug' => 'firewall-configuration-management',
                'title' => 'Firewall Configuration & Management',
                'icon' => 'services/firewall-configuration-management.png',
                'banner_image' => 'services/firewall-configuration-management.png',
                'sort_order' => 7,
                'short_description' => 'Firewall configuration and management for deployment, policy tuning, VPN, segmentation, monitoring, audits, and ongoing support.',
                'seo_title' => 'Firewall Configuration & Management in Navi Mumbai | Tectignis',
                'seo_description' => 'Firewall configuration and management in Navi Mumbai for Fortinet, Palo Alto, Cisco, VPN, rules, audits, monitoring, segmentation, and support.',
                'heading' => 'Firewall Configuration and Management for Stronger Network Control',
                'intro' => 'A firewall only protects you when policies, access, VPN, and monitoring are correctly configured. We set up and manage firewalls so your network stays controlled, visible, and easier to secure.',
                'bullets' => [
                    'Firewall setup, rule design, VPN, and segmentation',
                    'Policy reviews that remove risky or unused access',
                    'Monitoring, updates, backups, and support',
                ],
                'sub_services' => [
                    ['title' => 'Firewall Deployment', 'description' => 'Install and configure firewalls for office, data center, branch, or cloud-connected networks.'],
                    ['title' => 'Rule and Policy Design', 'description' => 'Create clean access rules for users, servers, applications, vendors, and branches.'],
                    ['title' => 'VPN Configuration', 'description' => 'Set up secure site-to-site and remote access VPNs with user and device controls.'],
                    ['title' => 'Network Segmentation', 'description' => 'Separate departments, servers, guests, CCTV, and critical systems to reduce exposure.'],
                    ['title' => 'Firewall Audit', 'description' => 'Review old rules, open ports, NAT, admin access, logging, firmware, and risky exceptions.'],
                    ['title' => 'Managed Firewall Support', 'description' => 'Handle monitoring, backups, updates, incident response, and policy change requests.'],
                ],
                'why_points' => [
                    'Firewall rules documented clearly so future changes are safer',
                    'Vendor experience across Fortinet, Palo Alto, Cisco, and similar platforms',
                    'Remote access and branch connectivity planned with security controls',
                    'Regular reviews to remove stale rules and reduce attack surface',
                    'Operational support for changes, troubleshooting, backups, and alerts',
                ],
                'faqs' => [
                    ['question' => 'Can you audit our existing firewall rules?', 'answer' => 'Yes. We review rules, NAT, open ports, VPN, firmware, admin access, logs, and risky exceptions.'],
                    ['question' => 'Can you configure VPN access?', 'answer' => 'Yes. We configure site-to-site VPNs, remote user VPNs, access controls, and logging.'],
                    ['question' => 'Do you support Fortinet or Palo Alto?', 'answer' => 'Yes. We work with Fortinet, Palo Alto, Cisco, and other common firewall platforms.'],
                    ['question' => 'Can you manage ongoing firewall changes?', 'answer' => 'Yes. We can support policy changes, monitoring, backups, updates, and incident troubleshooting.'],
                ],
                'tech_stacks' => ['Fortinet', 'Palo Alto', 'Cisco', 'Juniper', 'Linux', 'Microsoft'],
                'industries' => ['Corporate Offices', 'Manufacturing', 'Healthcare', 'Finance & Banking', 'Education'],
                'cta_heading' => 'Ready to Clean Up and Strengthen Your Firewall Rules?',
            ],
            [
                'slug' => 'soc-support',
                'title' => 'SOC (Security Operations Center) Support',
                'icon' => 'services/soc-support.png',
                'banner_image' => 'services/soc-support.png',
                'sort_order' => 8,
                'short_description' => 'SOC support for monitoring, alert triage, log review, threat detection, incident response coordination, and security reporting.',
                'seo_title' => 'SOC Support Services in Navi Mumbai | Tectignis',
                'seo_description' => 'SOC support services in Navi Mumbai for security monitoring, alert triage, log review, threat detection, incident response, SIEM, and reporting.',
                'heading' => 'SOC Support That Helps You Detect and Respond Faster',
                'intro' => 'Security tools generate value only when someone watches, investigates, and acts on the signals. We provide SOC support to help teams monitor alerts, review logs, detect threats, and coordinate response.',
                'bullets' => [
                    'Security monitoring and alert triage',
                    'Log review, threat detection, and incident coordination',
                    'Operational reports for visibility and governance',
                ],
                'sub_services' => [
                    ['title' => 'Alert Monitoring', 'description' => 'Track security alerts from firewalls, endpoints, cloud, servers, and monitoring tools.'],
                    ['title' => 'Log Review and Correlation', 'description' => 'Review logs and connect events across systems to identify suspicious activity.'],
                    ['title' => 'Threat Triage', 'description' => 'Classify alerts, remove noise, prioritize real issues, and recommend next steps.'],
                    ['title' => 'Incident Response Coordination', 'description' => 'Support containment, evidence gathering, communication, and recovery during security incidents.'],
                    ['title' => 'Vulnerability Follow-Up', 'description' => 'Track critical weaknesses, patch status, exposed services, and recurring risks.'],
                    ['title' => 'SOC Reporting', 'description' => 'Deliver reports on alerts, incidents, response times, open risks, and improvement actions.'],
                ],
                'why_points' => [
                    'SOC support that complements your internal IT team instead of replacing context',
                    'Triage process focused on actionable alerts and business impact',
                    'Clear escalation paths for containment, communication, and recovery',
                    'Visibility reports that help management understand security operations',
                    'Flexible support levels for growing companies without a full in-house SOC',
                ],
                'faqs' => [
                    ['question' => 'Do we need a SIEM before using SOC support?', 'answer' => 'Not always. We can begin with available logs and tools, then recommend SIEM improvements as your maturity grows.'],
                    ['question' => 'Can SOC support work with our IT team?', 'answer' => 'Yes. We coordinate with internal IT for triage, containment, patching, evidence, and recovery steps.'],
                    ['question' => 'Can you review firewall and endpoint alerts?', 'answer' => 'Yes. We can monitor and review alerts from supported firewalls, endpoints, servers, cloud, and log sources.'],
                    ['question' => 'Do you provide security reports?', 'answer' => 'Yes. Reports can cover alerts, incidents, recurring risks, response status, open items, and improvement recommendations.'],
                ],
                'tech_stacks' => ['Fortinet', 'Palo Alto', 'Cisco', 'Microsoft', 'AWS', 'Linux'],
                'industries' => ['Finance & Banking', 'Healthcare', 'Corporate Offices', 'Manufacturing', 'Government'],
                'cta_heading' => 'Ready to Improve Security Monitoring and Response?',
            ],
        ];
    }
}
