<?php

namespace Database\Seeders;

use App\Models\Industry;
use Illuminate\Database\Seeder;

class IndustryContentSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = $this->profiles();

        foreach (Industry::query()->select(['id', 'slug', 'name', 'short_description'])->lazyById() as $industry) {
            $profile = $profiles[$industry->slug] ?? $this->genericProfile($industry->name, $industry->short_description);

            $industry->update([
                'short_description' => $profile['short_description'],
                'seo_title' => $profile['seo_title'],
                'seo_description' => $profile['seo_description'],
                'seo_keywords' => $profile['seo_keywords'],
                'content' => $this->buildContent($profile),
            ]);
        }
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    private function profiles(): array
    {
        return [
            'manufacturing' => [
                'short_description' => 'Connected manufacturing systems that improve production visibility, quality control, and operational resilience.',
                'seo_title' => 'Manufacturing Software and IT Solutions | Tectignis',
                'seo_description' => 'Modernize manufacturing operations with connected production, inventory, quality, and infrastructure solutions from Tectignis.',
                'seo_keywords' => 'manufacturing software, production automation, ERP, inventory management, industrial IT solutions',
                'eyebrow' => 'MANUFACTURING TECHNOLOGY SOLUTIONS',
                'heading' => 'Connected Operations. Stronger Manufacturing.',
                'highlight' => 'Stronger Manufacturing.',
                'intro' => 'Bring production, inventory, quality, and teams into one dependable operating rhythm with technology designed around your factory floor.',
                'features' => ['Improve production visibility', 'Reduce manual handoffs', 'Protect critical operations', 'Scale across plants'],
                'badges' => ['Production Intelligence', 'Quality Control', 'Secure Infrastructure', 'Operational Support'],
                'challenge_heading' => 'Production Demands. Constant Pressure.',
                'challenge_intro' => 'Manufacturers need real-time control while managing complex processes, changing demand, and tight delivery commitments.',
                'challenges' => ['Disconnected production and inventory data', 'Manual reporting that delays decisions', 'Inconsistent quality and traceability', 'Unplanned equipment or network downtime', 'Complex vendor and supply-chain coordination', 'Growing pressure on cost and delivery timelines'],
                'solution_heading' => 'Technology Built for Better Production Control',
                'solutions' => [
                    ['title' => 'Manufacturing ERP', 'description' => 'Connect planning, purchasing, production, inventory, and reporting in one operating system.'],
                    ['title' => 'Production Tracking', 'description' => 'Capture output, work orders, shifts, downtime, and exceptions as work happens.'],
                    ['title' => 'Inventory and Warehouse Control', 'description' => 'Keep materials, spares, finished goods, and transfers visible across locations.'],
                    ['title' => 'Quality Management', 'description' => 'Standardize inspections, checklists, approvals, and traceability for every batch.'],
                    ['title' => 'Industrial Network Security', 'description' => 'Strengthen the infrastructure that keeps plant systems connected and protected.'],
                    ['title' => 'Analytics and Dashboards', 'description' => 'Turn operational data into clear views of output, waste, delays, and trends.'],
                ],
                'stats' => [['value' => 'Real-time', 'label' => 'Production Visibility'], ['value' => 'One View', 'label' => 'Operations and Inventory'], ['value' => '24/7', 'label' => 'Business-Critical Support'], ['value' => 'Fewer', 'label' => 'Manual Handoffs'], ['value' => 'Clearer', 'label' => 'Quality Traceability'], ['value' => 'Scalable', 'label' => 'Multi-Plant Operations']],
                'grid' => ['Production Planning', 'Shop-Floor Tracking', 'Inventory Management', 'Quality Control', 'Maintenance Workflows', 'Industrial Networking', 'Data Backup and Recovery', 'Operational Analytics'],
                'faqs' => [
                    ['question' => 'Can the system work with our existing production process?', 'answer' => 'Yes. We map current workflows first, then configure or develop the modules, approvals, reports, and integrations your teams actually need.'],
                    ['question' => 'Can we track multiple plants or warehouses?', 'answer' => 'Yes. The solution can separate locations while giving management a consolidated view of stock, production, and performance.'],
                    ['question' => 'How do you improve production data accuracy?', 'answer' => 'We replace duplicate entries and disconnected spreadsheets with role-based workflows, validation, and real-time reporting.'],
                    ['question' => 'Can manufacturing systems integrate with existing software?', 'answer' => 'Yes. We assess available APIs, exports, devices, and data formats to create practical integrations with ERP, accounting, or shop-floor tools.'],
                ],
                'faq_cta_heading' => 'Ready to Modernize Your Manufacturing Operations?',
                'faq_cta_text' => 'Build a connected operational foundation that gives your teams clearer control from planning through dispatch.',
                'cta_heading' => 'Build a More Connected Manufacturing Operation',
                'cta_subtitle' => 'Talk with our team about the systems, infrastructure, and automation that fit your production goals.',
            ],
            'healthcare' => [
                'short_description' => 'Secure healthcare technology for better patient journeys, clinical coordination, and operational control.',
                'seo_title' => 'Healthcare Software and IT Solutions | Tectignis',
                'seo_description' => 'Improve patient, clinical, and operational workflows with secure healthcare software and IT solutions from Tectignis.',
                'seo_keywords' => 'healthcare software, hospital management system, telemedicine, clinic software, healthcare IT security',
                'eyebrow' => 'HEALTHCARE TECHNOLOGY SOLUTIONS',
                'heading' => 'Connected Care. Confident Healthcare Teams.',
                'highlight' => 'Confident Healthcare Teams.',
                'intro' => 'Make every patient interaction and back-office process easier to manage with secure systems that keep care teams informed and responsive.',
                'features' => ['Unify patient journeys', 'Secure sensitive records', 'Improve clinical coordination', 'Reduce administrative load'],
                'badges' => ['Patient-Centered Care', 'Secure Records', 'Connected Departments', 'Reliable Support'],
                'challenge_heading' => 'Patient Expectations. Complex Operations.',
                'challenge_intro' => 'Healthcare organizations must deliver responsive care while protecting information and keeping clinical, financial, and support teams aligned.',
                'challenges' => ['Fragmented patient information across departments', 'Manual appointment and billing processes', 'Pressure to protect confidential health data', 'Long waits and inconsistent patient communication', 'Complex pharmacy, lab, and inventory workflows', 'Limited visibility into operational performance'],
                'solution_heading' => 'Digital Foundations for Better Care Delivery',
                'solutions' => [
                    ['title' => 'Hospital and Clinic Management', 'description' => 'Coordinate registration, appointments, billing, pharmacy, lab, and patient records.'],
                    ['title' => 'Patient Portals', 'description' => 'Give patients easier access to appointments, updates, documents, and follow-up information.'],
                    ['title' => 'Telemedicine Platforms', 'description' => 'Extend care with secure virtual consultations and connected care pathways.'],
                    ['title' => 'Clinical Workflow Automation', 'description' => 'Standardize handoffs, approvals, reminders, and documentation across care teams.'],
                    ['title' => 'Healthcare Data Security', 'description' => 'Protect records with role-based access, backup, monitoring, and infrastructure controls.'],
                    ['title' => 'Operational Dashboards', 'description' => 'Monitor patient flow, collections, utilization, stock, and service performance.'],
                ],
                'stats' => [['value' => 'One Record', 'label' => 'Across Care Teams'], ['value' => 'Faster', 'label' => 'Patient Coordination'], ['value' => 'Secure', 'label' => 'Role-Based Access'], ['value' => 'Real-time', 'label' => 'Operational Insight'], ['value' => 'Better', 'label' => 'Patient Communication'], ['value' => 'Scalable', 'label' => 'Care Delivery']],
                'grid' => ['Hospital Management', 'Clinic and OPD Workflows', 'Appointment Systems', 'Pharmacy Management', 'Laboratory Integration', 'Telemedicine Platforms', 'Healthcare Cybersecurity', 'Patient Experience Portals'],
                'faqs' => [
                    ['question' => 'Can you build for both clinics and hospitals?', 'answer' => 'Yes. We adapt workflows for single clinics, diagnostic centers, multi-specialty hospitals, and multi-location healthcare groups.'],
                    ['question' => 'How do you protect patient data?', 'answer' => 'We apply role-based access, secure infrastructure, backups, audit-friendly processes, and security controls appropriate to your environment.'],
                    ['question' => 'Can you integrate lab, pharmacy, and billing workflows?', 'answer' => 'Yes. We can connect those departments so teams work from consistent patient and operational information.'],
                    ['question' => 'Can staff be trained during implementation?', 'answer' => 'Yes. We plan rollout, migration, training, and support around the people who will use the system every day.'],
                ],
                'faq_cta_heading' => 'Ready to Improve the Care Experience?',
                'faq_cta_text' => 'Create a safer, more connected healthcare operation for patients, clinicians, and administrators.',
                'cta_heading' => 'Let Technology Make Care Easier to Deliver',
                'cta_subtitle' => 'Partner with experts who understand the balance between patient experience, security, and operational reality.',
            ],
            'education' => [
                'short_description' => 'Learning and campus platforms that improve engagement, administration, and outcomes for modern institutions.',
                'seo_title' => 'Education Software and IT Solutions | Tectignis',
                'seo_description' => 'Deliver better learning and smoother campus operations with LMS, school ERP, and education technology solutions from Tectignis.',
                'seo_keywords' => 'education software, LMS development, school ERP, e-learning platform, campus management system',
                'eyebrow' => 'EDUCATION TECHNOLOGY SOLUTIONS',
                'heading' => 'Better Learning. Better Connected Institutions.',
                'highlight' => 'Better Connected Institutions.',
                'intro' => 'Give educators, learners, and administrators the systems they need to teach, learn, communicate, and manage every academic day with confidence.',
                'features' => ['Engage every learner', 'Simplify administration', 'Connect campus communities', 'Measure learning progress'],
                'badges' => ['Digital Learning', 'Campus Operations', 'Parent Communication', 'Learning Analytics'],
                'challenge_heading' => 'Growing Expectations. Disconnected Systems.',
                'challenge_intro' => 'Institutions need to serve diverse learners while managing courses, administration, communication, and reporting without creating more work for staff.',
                'challenges' => ['Learning materials spread across multiple tools', 'Manual admissions, fees, and attendance processes', 'Limited visibility into learner progress', 'Inconsistent communication with parents and students', 'Complex examination and certification workflows', 'Need for secure access across campus and remote learning'],
                'solution_heading' => 'Technology That Supports Every Learning Journey',
                'solutions' => [
                    ['title' => 'Learning Management Systems', 'description' => 'Organize courses, content, assessments, progress, and certificates in one place.'],
                    ['title' => 'School and College ERP', 'description' => 'Simplify admissions, attendance, fees, timetables, and administrative workflows.'],
                    ['title' => 'Student and Parent Portals', 'description' => 'Improve communication with timely updates, records, notices, and self-service access.'],
                    ['title' => 'Assessment Platforms', 'description' => 'Manage question banks, online tests, grading, results, and academic reporting.'],
                    ['title' => 'Campus Infrastructure', 'description' => 'Build dependable Wi-Fi, security, devices, and support for connected learning.'],
                    ['title' => 'Education Analytics', 'description' => 'Reveal attendance, engagement, performance, and operational trends for leaders.'],
                ],
                'stats' => [['value' => 'Anytime', 'label' => 'Learning Access'], ['value' => 'One Portal', 'label' => 'For Campus Communities'], ['value' => 'Clearer', 'label' => 'Learner Progress'], ['value' => 'Faster', 'label' => 'Administrative Workflows'], ['value' => 'Secure', 'label' => 'Academic Records'], ['value' => 'Scalable', 'label' => 'Digital Delivery']],
                'grid' => ['LMS Development', 'School ERP', 'Student Information Systems', 'Online Assessments', 'Virtual Classrooms', 'Parent Communication', 'Campus Networking', 'Learning Analytics'],
                'faqs' => [
                    ['question' => 'Can the platform support online and classroom learning?', 'answer' => 'Yes. We can build blended learning workflows that combine classes, content, assessments, attendance, and communication.'],
                    ['question' => 'Can different user roles have different access?', 'answer' => 'Yes. Administrators, teachers, students, parents, and finance teams can receive the access and tools relevant to them.'],
                    ['question' => 'Can we migrate existing student information?', 'answer' => 'Yes. We review available records and plan a careful import so useful information is clean and accessible in the new system.'],
                    ['question' => 'Can the solution grow with our institution?', 'answer' => 'Yes. We can launch essential modules first and add learning, analytics, communication, or campus capabilities in phases.'],
                ],
                'faq_cta_heading' => 'Ready to Create a Better Learning Experience?',
                'faq_cta_text' => 'Build an education platform that makes learning and campus operations work together.',
                'cta_heading' => 'Make Every Learning Experience More Connected',
                'cta_subtitle' => 'Design the digital tools your institution needs to engage learners and support educators.',
            ],
            'retail' => [
                'short_description' => 'Retail systems that connect stores, stock, customers, and teams for smoother daily operations.',
                'seo_title' => 'Retail Software and IT Solutions | Tectignis',
                'seo_description' => 'Connect retail stores, inventory, point of sale, and customer experiences with practical technology solutions from Tectignis.',
                'seo_keywords' => 'retail software, POS system, inventory management, retail ERP, customer loyalty platform',
                'eyebrow' => 'RETAIL TECHNOLOGY SOLUTIONS',
                'heading' => 'Connected Stores. Better Every-Day Retail.',
                'highlight' => 'Better Every-Day Retail.',
                'intro' => 'Unify store operations, inventory, customer experiences, and reporting so your teams can serve shoppers quickly and make smarter decisions.',
                'features' => ['Unify store operations', 'Keep stock accurate', 'Improve shopper journeys', 'See performance faster'],
                'badges' => ['Point of Sale', 'Inventory Visibility', 'Customer Loyalty', 'Multi-Store Control'],
                'challenge_heading' => 'Fast-Moving Retail. Little Room for Error.',
                'challenge_intro' => 'Retail teams need accurate stock, reliable systems, and timely insight while responding to changing customer expectations every day.',
                'challenges' => ['Stock differences across stores and channels', 'Slow or disconnected checkout workflows', 'Manual replenishment and purchase planning', 'Limited visibility into store-level performance', 'Inconsistent customer and loyalty experiences', 'Pressure to manage online and offline orders together'],
                'solution_heading' => 'Retail Systems Designed Around the Customer Journey',
                'solutions' => [
                    ['title' => 'Point of Sale Systems', 'description' => 'Process sales, returns, offers, and payments with fast, dependable store workflows.'],
                    ['title' => 'Inventory Management', 'description' => 'Track stock movement, counts, transfers, reorders, and availability in real time.'],
                    ['title' => 'Retail ERP', 'description' => 'Connect purchasing, suppliers, stores, finance, and reporting across the business.'],
                    ['title' => 'Customer Loyalty Platforms', 'description' => 'Create more relevant repeat experiences with profiles, rewards, and campaigns.'],
                    ['title' => 'Omnichannel Commerce', 'description' => 'Coordinate online orders, store fulfillment, and customer communication across channels.'],
                    ['title' => 'Retail Analytics', 'description' => 'Understand sales, margins, stock movement, promotions, and store performance clearly.'],
                ],
                'stats' => [['value' => 'Live', 'label' => 'Store and Stock Visibility'], ['value' => 'Faster', 'label' => 'Checkout Workflows'], ['value' => 'One View', 'label' => 'Across Sales Channels'], ['value' => 'Smarter', 'label' => 'Replenishment Decisions'], ['value' => 'Better', 'label' => 'Customer Experiences'], ['value' => 'Scalable', 'label' => 'Multi-Store Growth']],
                'grid' => ['Point of Sale', 'Retail ERP', 'Inventory Control', 'Barcode Workflows', 'Customer Loyalty', 'E-commerce Integration', 'Store Networking', 'Sales Analytics'],
                'faqs' => [
                    ['question' => 'Can the system manage multiple stores?', 'answer' => 'Yes. You can manage stores, warehouses, transfers, stock, pricing, and reporting from a central platform.'],
                    ['question' => 'Can POS connect with inventory and e-commerce?', 'answer' => 'Yes. We can integrate point of sale, stock, online orders, and reporting so teams see a consistent picture.'],
                    ['question' => 'Can the solution support barcode scanning?', 'answer' => 'Yes. Barcode or QR workflows can support receiving, counts, checkout, transfers, and fulfillment.'],
                    ['question' => 'Can reports be tailored to our retail operation?', 'answer' => 'Yes. We can create dashboards around sales, margins, stock aging, store performance, and the KPIs your leaders use.'],
                ],
                'faq_cta_heading' => 'Ready to Make Retail Operations Easier?',
                'faq_cta_text' => 'Connect the systems your stores and customers rely on every day.',
                'cta_heading' => 'Give Your Retail Teams a Clearer View of Every Day',
                'cta_subtitle' => 'Talk to us about practical systems for stores, stock, customers, and growth.',
            ],
            'real-estate' => [
                'short_description' => 'Real estate platforms that organize leads, properties, transactions, and service experiences in one place.',
                'seo_title' => 'Real Estate Software and IT Solutions | Tectignis',
                'seo_description' => 'Improve property, lead, sales, and customer workflows with tailored real estate software and IT solutions from Tectignis.',
                'seo_keywords' => 'real estate software, property management system, real estate CRM, broker portal, property sales platform',
                'eyebrow' => 'REAL ESTATE TECHNOLOGY SOLUTIONS',
                'heading' => 'Smarter Property Operations. Stronger Relationships.',
                'highlight' => 'Stronger Relationships.',
                'intro' => 'Bring leads, listings, sales, documentation, and customer service into a connected experience built around the way your property business works.',
                'features' => ['Organize every lead', 'Manage properties clearly', 'Accelerate sales follow-up', 'Improve buyer experiences'],
                'badges' => ['Property Management', 'Lead Intelligence', 'Sales Automation', 'Client Portals'],
                'challenge_heading' => 'Many Properties. Too Many Disconnected Touchpoints.',
                'challenge_intro' => 'Real estate teams need to manage complex sales cycles and property information while giving prospects timely, confident service.',
                'challenges' => ['Leads lost between campaigns and sales teams', 'Property information scattered across files', 'Manual follow-ups and booking processes', 'Limited visibility into sales pipeline health', 'Complex documents, payments, and handovers', 'Inconsistent communication with buyers and channel partners'],
                'solution_heading' => 'Digital Tools for More Confident Property Decisions',
                'solutions' => [
                    ['title' => 'Real Estate CRM', 'description' => 'Track inquiries, site visits, follow-ups, bookings, and conversion activity in one place.'],
                    ['title' => 'Property Management Systems', 'description' => 'Maintain property, unit, availability, documentation, and service information clearly.'],
                    ['title' => 'Broker and Channel Partner Portals', 'description' => 'Give partners timely access to inventory, leads, documents, and performance information.'],
                    ['title' => 'Customer Portals', 'description' => 'Make documents, payments, updates, and service requests easier for buyers to manage.'],
                    ['title' => 'Digital Sales Experiences', 'description' => 'Create websites, landing pages, and tools that turn interest into qualified conversations.'],
                    ['title' => 'Sales and Project Analytics', 'description' => 'See pipeline, source, inventory, booking, and project trends without manual reporting.'],
                ],
                'stats' => [['value' => 'One View', 'label' => 'Of Leads and Inventory'], ['value' => 'Faster', 'label' => 'Sales Follow-Up'], ['value' => 'Clearer', 'label' => 'Project Visibility'], ['value' => 'Better', 'label' => 'Buyer Communication'], ['value' => 'Secure', 'label' => 'Document Workflows'], ['value' => 'Scalable', 'label' => 'Property Portfolios']],
                'grid' => ['Real Estate CRM', 'Property Listings', 'Lead Management', 'Broker Portals', 'Customer Portals', 'Booking and Payments', 'Document Management', 'Sales Analytics'],
                'faqs' => [
                    ['question' => 'Can the system track leads from multiple channels?', 'answer' => 'Yes. We can bring website inquiries, campaign leads, partner referrals, calls, and walk-ins into a structured sales workflow.'],
                    ['question' => 'Can buyers access their documents and updates?', 'answer' => 'Yes. A customer portal can provide secure access to relevant documents, updates, payment information, and service requests.'],
                    ['question' => 'Can you support brokers and channel partners?', 'answer' => 'Yes. Partner portals can make inventory, lead registration, collateral, and performance information easier to manage.'],
                    ['question' => 'Can the solution match our existing sales process?', 'answer' => 'Yes. We tailor stages, approvals, reports, roles, and integrations to the way your team sells and services properties.'],
                ],
                'faq_cta_heading' => 'Ready to Put Every Property Opportunity in One View?',
                'faq_cta_text' => 'Create a more organized journey for your sales team, partners, and buyers.',
                'cta_heading' => 'Build a Real Estate Experience That Keeps Everyone Connected',
                'cta_subtitle' => 'Turn property, sales, and customer information into a more confident way of working.',
            ],
            'logistics' => [
                'short_description' => 'Logistics systems that improve shipment visibility, warehouse control, fleet coordination, and delivery performance.',
                'seo_title' => 'Logistics Software and IT Solutions | Tectignis',
                'seo_description' => 'Improve fleet, warehouse, shipment, and delivery operations with connected logistics software and IT solutions from Tectignis.',
                'seo_keywords' => 'logistics software, fleet management, warehouse management system, transport management, supply chain visibility',
                'eyebrow' => 'LOGISTICS TECHNOLOGY SOLUTIONS',
                'heading' => 'Every Move Visible. Every Delivery More Controlled.',
                'highlight' => 'Every Delivery More Controlled.',
                'intro' => 'Connect dispatch, fleet, warehouse, and customer updates so your operation can move faster with fewer blind spots and avoidable delays.',
                'features' => ['Track every movement', 'Coordinate teams faster', 'Improve warehouse accuracy', 'Keep customers informed'],
                'badges' => ['Fleet Visibility', 'Warehouse Control', 'Delivery Intelligence', 'Connected Operations'],
                'challenge_heading' => 'Moving Parts. Tight Delivery Commitments.',
                'challenge_intro' => 'Logistics teams must respond quickly to changing routes, inventory, drivers, and customer expectations while maintaining control of every handoff.',
                'challenges' => ['Limited real-time shipment and fleet visibility', 'Manual dispatch and proof-of-delivery processes', 'Warehouse stock and fulfillment errors', 'Disconnected customer communication', 'Inefficient route and capacity planning', 'Difficulty measuring operational performance'],
                'solution_heading' => 'Technology for More Predictable Logistics Operations',
                'solutions' => [
                    ['title' => 'Transport Management Systems', 'description' => 'Plan dispatch, loads, routes, documents, and delivery workflows in one system.'],
                    ['title' => 'Fleet Tracking', 'description' => 'Improve visibility into vehicles, movement, utilization, and delivery status.'],
                    ['title' => 'Warehouse Management', 'description' => 'Control receiving, storage, picking, packing, transfers, and dispatch accuracy.'],
                    ['title' => 'Customer Shipment Portals', 'description' => 'Provide customers with timely tracking, documents, updates, and service visibility.'],
                    ['title' => 'Proof of Delivery Workflows', 'description' => 'Capture signatures, photos, exceptions, and confirmations as deliveries happen.'],
                    ['title' => 'Logistics Analytics', 'description' => 'Monitor on-time performance, costs, capacity, exceptions, and operational trends.'],
                ],
                'stats' => [['value' => 'Live', 'label' => 'Shipment Visibility'], ['value' => 'Faster', 'label' => 'Dispatch Coordination'], ['value' => 'Clearer', 'label' => 'Warehouse Control'], ['value' => 'Timely', 'label' => 'Customer Updates'], ['value' => 'Smarter', 'label' => 'Route Decisions'], ['value' => 'Scalable', 'label' => 'Delivery Operations']],
                'grid' => ['Transport Management', 'Fleet Tracking', 'Warehouse Management', 'Route Planning', 'Proof of Delivery', 'Shipment Portals', 'Barcode Workflows', 'Logistics Analytics'],
                'faqs' => [
                    ['question' => 'Can the solution track fleet and shipment activity?', 'answer' => 'Yes. We can connect appropriate tracking data, status workflows, and dashboards so dispatchers and customers see meaningful updates.'],
                    ['question' => 'Can warehouses and transport operations use the same platform?', 'answer' => 'Yes. We can connect inventory, picking, dispatch, and delivery processes to reduce disconnected handoffs.'],
                    ['question' => 'Can drivers use mobile workflows?', 'answer' => 'Yes. Mobile workflows can support task updates, proof of delivery, exception reporting, and document capture.'],
                    ['question' => 'Can reports show delivery performance?', 'answer' => 'Yes. We can configure dashboards for on-time delivery, delays, route performance, costs, and exception patterns.'],
                ],
                'faq_cta_heading' => 'Ready to See More of Every Move?',
                'faq_cta_text' => 'Build the connected workflows that help your logistics operation stay visible and responsive.',
                'cta_heading' => 'Move Your Logistics Operation Forward With Confidence',
                'cta_subtitle' => 'Bring fleet, warehouse, dispatch, and customer information into one clearer operation.',
            ],
            'hospitality' => [
                'short_description' => 'Hospitality platforms that make bookings, guest service, operations, and property performance easier to manage.',
                'seo_title' => 'Hospitality Software and IT Solutions | Tectignis',
                'seo_description' => 'Improve booking, guest experience, property operations, and hospitality technology with solutions from Tectignis.',
                'seo_keywords' => 'hospitality software, hotel management system, booking engine, guest experience platform, property management system',
                'eyebrow' => 'HOSPITALITY TECHNOLOGY SOLUTIONS',
                'heading' => 'Memorable Guest Experiences. Better Managed Operations.',
                'highlight' => 'Better Managed Operations.',
                'intro' => 'Create a more seamless journey for guests and a more controlled day for your teams with connected booking, service, and property systems.',
                'features' => ['Simplify guest journeys', 'Coordinate property teams', 'Grow direct bookings', 'Protect service quality'],
                'badges' => ['Guest Experience', 'Booking Intelligence', 'Property Operations', 'Always-On Support'],
                'challenge_heading' => 'High Expectations. Constantly Changing Operations.',
                'challenge_intro' => 'Hospitality teams balance guest demands, bookings, service coordination, and property operations in an environment where every detail matters.',
                'challenges' => ['Disconnected booking and guest communication', 'Manual front-desk and service coordination', 'Limited view of occupancy and revenue trends', 'Inconsistent guest experiences across channels', 'Complex maintenance and property operations', 'Need for secure, dependable Wi-Fi and IT systems'],
                'solution_heading' => 'Technology That Makes Every Stay Smoother',
                'solutions' => [
                    ['title' => 'Property Management Systems', 'description' => 'Coordinate reservations, check-in, housekeeping, billing, and property activity.'],
                    ['title' => 'Booking Engines', 'description' => 'Create direct booking journeys that are simple, responsive, and aligned with your brand.'],
                    ['title' => 'Guest Experience Platforms', 'description' => 'Manage requests, communication, offers, feedback, and service touchpoints more smoothly.'],
                    ['title' => 'Restaurant and POS Systems', 'description' => 'Support orders, billing, inventory, and service workflows across food and beverage operations.'],
                    ['title' => 'Hospitality Infrastructure', 'description' => 'Strengthen Wi-Fi, networking, security, and support across guest and back-office spaces.'],
                    ['title' => 'Revenue and Operations Analytics', 'description' => 'Track occupancy, bookings, service performance, and operational trends in one view.'],
                ],
                'stats' => [['value' => 'Seamless', 'label' => 'Guest Journeys'], ['value' => 'Faster', 'label' => 'Team Coordination'], ['value' => 'Clearer', 'label' => 'Property Visibility'], ['value' => 'Better', 'label' => 'Direct Booking Experiences'], ['value' => 'Reliable', 'label' => 'Guest Connectivity'], ['value' => 'Scalable', 'label' => 'Hospitality Operations']],
                'grid' => ['Property Management', 'Booking Engines', 'Guest Portals', 'Restaurant POS', 'Housekeeping Workflows', 'Hospitality Wi-Fi', 'Access and Security', 'Revenue Analytics'],
                'faqs' => [
                    ['question' => 'Can you support hotels, resorts, and restaurants?', 'answer' => 'Yes. We tailor the mix of booking, property, guest, POS, infrastructure, and support services to your operation.'],
                    ['question' => 'Can booking and property operations be connected?', 'answer' => 'Yes. We can connect the booking journey with operational workflows so teams work from timely guest and reservation information.'],
                    ['question' => 'Can you improve guest Wi-Fi and technology reliability?', 'answer' => 'Yes. We assess connectivity, network design, security, and support requirements for guests and staff.'],
                    ['question' => 'Can the platform support more than one property?', 'answer' => 'Yes. Multi-property access and consolidated reporting can be designed around your management structure.'],
                ],
                'faq_cta_heading' => 'Ready to Elevate the Guest Experience?',
                'faq_cta_text' => 'Connect the technology behind bookings, service, and property performance.',
                'cta_heading' => 'Make Every Guest Journey Feel More Seamless',
                'cta_subtitle' => 'Create hospitality systems that work quietly and reliably behind a great stay.',
            ],
            'corporate-offices' => [
                'short_description' => 'Secure, connected workplace technology that improves productivity, collaboration, and day-to-day IT operations.',
                'seo_title' => 'Corporate Office IT Solutions | Tectignis',
                'seo_description' => 'Build secure, connected, high-performing workplaces with corporate IT infrastructure, security, cloud, and support solutions from Tectignis.',
                'seo_keywords' => 'corporate office IT solutions, workplace technology, IT infrastructure, cybersecurity, helpdesk support',
                'eyebrow' => 'CORPORATE OFFICE IT SOLUTIONS',
                'heading' => 'Smart Technology. Stronger Corporate Offices.',
                'highlight' => 'Corporate Offices.',
                'intro' => 'Build a secure, connected, high-performing workplace with technology that helps your people collaborate, stay productive, and grow with confidence.',
                'features' => ['Enhance workplace productivity', 'Secure data and infrastructure', 'Streamline IT operations', 'Enable seamless collaboration'],
                'badges' => ['Smart Workspaces', 'Secure Infrastructure', 'Seamless Collaboration', 'IT Management and Support'],
                'challenge_heading' => 'Modern Workplaces. New-Age Challenges.',
                'challenge_intro' => 'Corporate offices face evolving demands as teams, tools, and threats grow more complex every year.',
                'challenges' => ['Managing hybrid and remote workforces', 'Ensuring data security and compliance', 'Maintaining complex IT infrastructure', 'Enabling seamless team collaboration', 'Controlling rising operational and IT costs', 'Keeping workplace systems reliable as teams grow'],
                'solution_heading' => 'IT Solutions for High-Performing Corporate Offices',
                'solutions' => [
                    ['title' => 'IT Infrastructure Management', 'description' => 'Design and maintain dependable infrastructure for uninterrupted business operations.'],
                    ['title' => 'Unified Communication', 'description' => 'Connect teams across locations with integrated voice, video, and messaging.'],
                    ['title' => 'Cybersecurity Solutions', 'description' => 'Protect data and systems with layered, proactive security controls.'],
                    ['title' => 'Cloud and Workplace Solutions', 'description' => 'Create flexible cloud workspaces that support hybrid and remote teams.'],
                    ['title' => 'Helpdesk and IT Support', 'description' => 'Give people responsive support that keeps everyday work moving.'],
                    ['title' => 'IT Strategy and Consulting', 'description' => 'Align technology decisions with business priorities and future growth.'],
                ],
                'stats' => [['value' => 'Connected', 'label' => 'Workplace Experiences'], ['value' => 'Secure', 'label' => 'Data and Infrastructure'], ['value' => 'Responsive', 'label' => 'IT Support'], ['value' => 'One View', 'label' => 'Of IT Operations'], ['value' => 'Flexible', 'label' => 'Hybrid Collaboration'], ['value' => 'Scalable', 'label' => 'Business Growth']],
                'grid' => ['Workplace Technology', 'Network and Infrastructure', 'Cybersecurity Services', 'Cloud Solutions', 'Collaboration Tools', 'IT Support and Helpdesk', 'Data Backup and Recovery', 'Compliance and Governance'],
                'faqs' => [
                    ['question' => 'How do you help secure our office network?', 'answer' => 'We assess your environment and apply layered controls such as network security, endpoint protection, access management, backups, and monitoring.'],
                    ['question' => 'Can you support hybrid and remote teams?', 'answer' => 'Yes. We can design secure cloud workspaces, collaboration tools, remote access, and support processes around your workforce.'],
                    ['question' => 'What IT support services do you provide?', 'answer' => 'Support can cover users, devices, networks, servers, cloud systems, cybersecurity, preventive maintenance, and planned improvements.'],
                    ['question' => 'Can you work with our existing IT setup?', 'answer' => 'Yes. We begin with an assessment, identify priorities, and create a practical roadmap that works with your current systems where possible.'],
                ],
                'faq_cta_heading' => 'Ready to Transform Your Corporate Office?',
                'faq_cta_text' => 'Build a smart, secure, future-ready workplace tailored to your people and goals.',
                'cta_heading' => 'Let Us Build a Smarter Workplace Together',
                'cta_subtitle' => 'Partner with experts to design a workplace that works as hard as your team does.',
            ],
            'finance-banking' => [
                'short_description' => 'Secure financial technology for trusted customer journeys, connected operations, and stronger governance.',
                'seo_title' => 'Finance and Banking Technology Solutions | Tectignis',
                'seo_description' => 'Strengthen banking and financial services with secure digital platforms, automation, data protection, and operational technology from Tectignis.',
                'seo_keywords' => 'fintech development, banking software, financial services technology, cybersecurity, digital lending platform',
                'eyebrow' => 'FINANCE AND BANKING TECHNOLOGY SOLUTIONS',
                'heading' => 'Trusted Transactions. Smarter Financial Services.',
                'highlight' => 'Smarter Financial Services.',
                'intro' => 'Create secure, responsive financial experiences while giving teams the systems, controls, and insight they need to operate with confidence.',
                'features' => ['Protect sensitive data', 'Simplify customer journeys', 'Automate critical workflows', 'Strengthen governance'],
                'badges' => ['Secure by Design', 'Digital Banking', 'Process Automation', 'Data Intelligence'],
                'challenge_heading' => 'High Trust. High Complexity.',
                'challenge_intro' => 'Financial organizations must keep experiences simple for customers while managing security, risk, data, and ever-changing operational demands.',
                'challenges' => ['Growing expectations for digital self-service', 'Complex compliance and audit requirements', 'Sensitive data and evolving cyber threats', 'Manual lending, onboarding, and approval workflows', 'Disconnected customer and operational data', 'Need for reliable, always-available systems'],
                'solution_heading' => 'Secure Technology for Confident Financial Operations',
                'solutions' => [
                    ['title' => 'Digital Customer Platforms', 'description' => 'Create secure self-service journeys for applications, documents, updates, and support.'],
                    ['title' => 'Lending and Workflow Automation', 'description' => 'Streamline onboarding, verification, approvals, disbursement, and servicing workflows.'],
                    ['title' => 'Financial Process Automation', 'description' => 'Reduce repetitive work with controlled, traceable, and efficient digital processes.'],
                    ['title' => 'Cybersecurity and Compliance', 'description' => 'Strengthen identity, access, monitoring, resilience, and governance controls.'],
                    ['title' => 'Data and Reporting Platforms', 'description' => 'Make operational and customer data easier to govern, understand, and act on.'],
                    ['title' => 'Cloud and Infrastructure Services', 'description' => 'Build resilient foundations that support secure, scalable financial operations.'],
                ],
                'stats' => [['value' => 'Secure', 'label' => 'Digital Experiences'], ['value' => 'Faster', 'label' => 'Approval Workflows'], ['value' => 'Clearer', 'label' => 'Operational Reporting'], ['value' => 'Stronger', 'label' => 'Governance Controls'], ['value' => 'Reliable', 'label' => 'Service Availability'], ['value' => 'Scalable', 'label' => 'Financial Platforms']],
                'grid' => ['Digital Onboarding', 'Lending Workflows', 'Customer Portals', 'Financial Automation', 'Cybersecurity', 'Identity and Access', 'Cloud Infrastructure', 'Risk and Reporting'],
                'faqs' => [
                    ['question' => 'How do you approach security for financial systems?', 'answer' => 'We design security into the solution through access controls, secure infrastructure, monitoring, backups, testing, and governance practices suited to the scope.'],
                    ['question' => 'Can you automate lending or approval workflows?', 'answer' => 'Yes. We can map decision points, documents, user roles, integrations, and audit needs to build controlled automation.'],
                    ['question' => 'Can the platform integrate with existing banking or financial tools?', 'answer' => 'Yes. We evaluate available APIs, data exports, and integration requirements before proposing a reliable approach.'],
                    ['question' => 'Can implementation be phased?', 'answer' => 'Yes. We can prioritize the highest-value customer, workflow, security, or reporting improvements and expand from there.'],
                ],
                'faq_cta_heading' => 'Ready to Modernize Financial Services With Confidence?',
                'faq_cta_text' => 'Build secure, customer-focused technology that gives your teams better control.',
                'cta_heading' => 'Create Financial Experiences People Can Trust',
                'cta_subtitle' => 'Bring security, service, and operational intelligence into a stronger digital foundation.',
            ],
            'ecommerce' => [
                'short_description' => 'E-commerce experiences and operations that connect storefronts, orders, inventory, and customer service.',
                'seo_title' => 'E-commerce Development and Technology Solutions | Tectignis',
                'seo_description' => 'Build, improve, and scale online stores, marketplaces, order management, and customer experiences with Tectignis.',
                'seo_keywords' => 'e-commerce development, online store, marketplace development, order management system, e-commerce integration',
                'eyebrow' => 'E-COMMERCE TECHNOLOGY SOLUTIONS',
                'heading' => 'Better Buying Experiences. Smarter E-commerce Operations.',
                'highlight' => 'Smarter E-commerce Operations.',
                'intro' => 'Create fast, reliable online shopping journeys while bringing orders, stock, fulfillment, and customer support into one connected operation.',
                'features' => ['Convert more confidently', 'Unify orders and stock', 'Simplify fulfillment', 'Build repeat customer value'],
                'badges' => ['Online Storefronts', 'Order Intelligence', 'Secure Payments', 'Scalable Growth'],
                'challenge_heading' => 'Fast-Growing Demand. Complex Commerce Operations.',
                'challenge_intro' => 'E-commerce teams must deliver smooth customer experiences while managing product data, stock, orders, fulfillment, and marketing across channels.',
                'challenges' => ['Disconnected storefront, inventory, and order data', 'Slow or inconsistent checkout experiences', 'Manual fulfillment and return workflows', 'Limited visibility across sales channels', 'Difficulty personalizing customer engagement', 'Pressure to keep performance and security reliable at scale'],
                'solution_heading' => 'Commerce Technology That Connects the Full Order Journey',
                'solutions' => [
                    ['title' => 'E-commerce Store Development', 'description' => 'Build responsive, conversion-focused storefronts tailored to your brand and customers.'],
                    ['title' => 'Marketplace Platforms', 'description' => 'Create multi-vendor experiences with product, seller, order, and payout workflows.'],
                    ['title' => 'Order Management Systems', 'description' => 'Coordinate orders, payments, fulfillment, returns, and customer updates in one view.'],
                    ['title' => 'Inventory Integration', 'description' => 'Keep availability accurate by connecting stores, warehouses, POS, and sales channels.'],
                    ['title' => 'Customer Experience Automation', 'description' => 'Improve communication, re-engagement, support, and loyalty through connected journeys.'],
                    ['title' => 'E-commerce Analytics', 'description' => 'Understand conversion, sales, products, channels, and fulfillment performance clearly.'],
                ],
                'stats' => [['value' => 'Faster', 'label' => 'Shopping Journeys'], ['value' => 'One View', 'label' => 'Of Orders and Stock'], ['value' => 'Better', 'label' => 'Customer Engagement'], ['value' => 'Clearer', 'label' => 'Fulfillment Visibility'], ['value' => 'Secure', 'label' => 'Commerce Workflows'], ['value' => 'Scalable', 'label' => 'Online Growth']],
                'grid' => ['Online Store Development', 'Marketplace Platforms', 'Order Management', 'Payment Integration', 'Inventory Integration', 'Customer Loyalty', 'Fulfillment Workflows', 'Commerce Analytics'],
                'faqs' => [
                    ['question' => 'Can you build a store around our specific business model?', 'answer' => 'Yes. We shape catalog, pricing, checkout, fulfillment, user roles, and integrations around the way you sell.'],
                    ['question' => 'Can online orders connect with our stock systems?', 'answer' => 'Yes. We can connect e-commerce with inventory, warehouse, POS, and ERP systems where appropriate.'],
                    ['question' => 'Can you support marketplaces as well as single-brand stores?', 'answer' => 'Yes. We can design the seller, catalog, order, commission, and payout workflows needed for marketplace operations.'],
                    ['question' => 'Can the platform grow as order volume increases?', 'answer' => 'Yes. We consider performance, integrations, infrastructure, and workflow scalability from the outset.'],
                ],
                'faq_cta_heading' => 'Ready to Make Online Commerce Easier to Run?',
                'faq_cta_text' => 'Connect the storefront and operational systems your customers and teams rely on.',
                'cta_heading' => 'Build an E-commerce Operation Ready for What Comes Next',
                'cta_subtitle' => 'Turn your online store into a more connected, dependable customer experience.',
            ],
            'government' => [
                'short_description' => 'Public-sector technology that makes citizen services, administration, and digital governance more accessible and secure.',
                'seo_title' => 'Government and Public Sector Technology Solutions | Tectignis',
                'seo_description' => 'Improve citizen services, digital governance, public administration, and secure infrastructure with solutions from Tectignis.',
                'seo_keywords' => 'e-governance solutions, government software, citizen services portal, public sector IT, digital transformation',
                'eyebrow' => 'GOVERNMENT TECHNOLOGY SOLUTIONS',
                'heading' => 'Accessible Services. Stronger Digital Governance.',
                'highlight' => 'Stronger Digital Governance.',
                'intro' => 'Design secure, inclusive digital services that help public teams serve citizens more effectively and manage complex administrative work with clarity.',
                'features' => ['Improve citizen access', 'Simplify public workflows', 'Strengthen data governance', 'Build trusted digital services'],
                'badges' => ['Citizen-Centered Design', 'Secure Platforms', 'Process Transparency', 'Scalable Delivery'],
                'challenge_heading' => 'Public Expectations. Complex Service Delivery.',
                'challenge_intro' => 'Public-sector organizations must make services accessible and reliable while coordinating departments, protecting data, and maintaining accountability.',
                'challenges' => ['Paper-heavy or fragmented citizen workflows', 'Complex approvals across departments', 'Need for accessible digital services', 'Sensitive public data and cybersecurity concerns', 'Limited visibility into service delivery performance', 'Legacy systems that are difficult to integrate or improve'],
                'solution_heading' => 'Technology That Makes Public Services Easier to Access',
                'solutions' => [
                    ['title' => 'Citizen Service Portals', 'description' => 'Create clear digital journeys for applications, requests, documents, updates, and support.'],
                    ['title' => 'E-Governance Workflows', 'description' => 'Digitize approvals, case management, notifications, and departmental handoffs.'],
                    ['title' => 'Public Information Platforms', 'description' => 'Make information, notices, forms, and resources easier for citizens to find and use.'],
                    ['title' => 'Data and Reporting Systems', 'description' => 'Give teams clearer views of service demand, progress, performance, and outcomes.'],
                    ['title' => 'Cybersecurity and Infrastructure', 'description' => 'Protect critical systems with secure access, resilient infrastructure, and proactive controls.'],
                    ['title' => 'Integration and Modernization', 'description' => 'Connect existing systems and introduce improvements in practical, manageable phases.'],
                ],
                'stats' => [['value' => 'Accessible', 'label' => 'Citizen Services'], ['value' => 'Clearer', 'label' => 'Process Visibility'], ['value' => 'Secure', 'label' => 'Public Information'], ['value' => 'Faster', 'label' => 'Administrative Workflows'], ['value' => 'Connected', 'label' => 'Departmental Services'], ['value' => 'Scalable', 'label' => 'Digital Delivery']],
                'grid' => ['Citizen Service Portals', 'E-Governance Workflows', 'Case Management', 'Digital Forms', 'Public Information Systems', 'Secure Infrastructure', 'Data Dashboards', 'Systems Integration'],
                'faqs' => [
                    ['question' => 'Can you modernize services without replacing everything at once?', 'answer' => 'Yes. We can identify priority journeys, connect existing systems where possible, and plan phased improvements that reduce delivery risk.'],
                    ['question' => 'How do you make services accessible to diverse users?', 'answer' => 'We focus on clear content, responsive interfaces, straightforward workflows, and appropriate accessibility considerations from the start.'],
                    ['question' => 'Can the platform support multiple departments?', 'answer' => 'Yes. We can design role-based workflows, shared data, integrations, and reporting around departmental responsibilities.'],
                    ['question' => 'How do you approach government data security?', 'answer' => 'We plan secure access, resilient hosting, monitoring, backup, and governance practices based on the system and its data requirements.'],
                ],
                'faq_cta_heading' => 'Ready to Make Public Services Easier to Access?',
                'faq_cta_text' => 'Build digital services that create a clearer experience for citizens and public teams.',
                'cta_heading' => 'Deliver Digital Public Services With Greater Confidence',
                'cta_subtitle' => 'Create secure, useful platforms that help your organization serve more effectively.',
            ],
            'startups' => [
                'short_description' => 'Practical product development and technology foundations for startups ready to validate, launch, and scale.',
                'seo_title' => 'Startup Product Development and Technology Solutions | Tectignis',
                'seo_description' => 'Validate, launch, and scale your product with startup-focused MVP development, automation, cloud, and technology support from Tectignis.',
                'seo_keywords' => 'startup app development, MVP development, SaaS development, startup technology partner, product development',
                'eyebrow' => 'STARTUP TECHNOLOGY SOLUTIONS',
                'heading' => 'Move From Idea to Momentum With Confidence.',
                'highlight' => 'Momentum With Confidence.',
                'intro' => 'Turn a promising idea into a focused, useful product with the engineering, design, and technology decisions needed to learn fast and grow wisely.',
                'features' => ['Validate ideas faster', 'Launch focused MVPs', 'Build for learning', 'Scale with clarity'],
                'badges' => ['MVP Delivery', 'Product Strategy', 'Cloud Ready', 'Growth Foundations'],
                'challenge_heading' => 'Big Ideas. Limited Time and Resources.',
                'challenge_intro' => 'Startups need to prove value quickly, make the right product choices, and create a technical foundation that will not hold them back later.',
                'challenges' => ['Turning a broad idea into a focused first release', 'Balancing speed, quality, and budget', 'Choosing technology that can grow with demand', 'Building feedback loops with early users', 'Managing product priorities as the market changes', 'Establishing dependable security and operations early'],
                'solution_heading' => 'Product and Technology Support for Every Growth Stage',
                'solutions' => [
                    ['title' => 'MVP Development', 'description' => 'Define and build the smallest valuable product that helps you learn from real users.'],
                    ['title' => 'Product Discovery', 'description' => 'Clarify users, problems, journeys, priorities, and success measures before development begins.'],
                    ['title' => 'Web and Mobile Applications', 'description' => 'Create responsive, user-focused products for customers, teams, and partners.'],
                    ['title' => 'SaaS Platform Development', 'description' => 'Build multi-user product foundations with roles, subscriptions, workflows, and analytics.'],
                    ['title' => 'Automation and Integrations', 'description' => 'Connect the tools and workflows that help small teams operate efficiently.'],
                    ['title' => 'Cloud and Growth Readiness', 'description' => 'Set up dependable infrastructure, monitoring, security, and scalability for the next stage.'],
                ],
                'stats' => [['value' => 'Focused', 'label' => 'MVP Scope'], ['value' => 'Faster', 'label' => 'Learning Cycles'], ['value' => 'Clearer', 'label' => 'Product Priorities'], ['value' => 'Flexible', 'label' => 'Technology Foundations'], ['value' => 'Connected', 'label' => 'Startup Workflows'], ['value' => 'Ready', 'label' => 'For Growth']],
                'grid' => ['Product Discovery', 'MVP Development', 'Web Applications', 'Mobile Applications', 'SaaS Platforms', 'Workflow Automation', 'Cloud Foundations', 'Product Analytics'],
                'faqs' => [
                    ['question' => 'How do you decide what belongs in an MVP?', 'answer' => 'We start with the user problem and business goal, then prioritize the smallest set of capabilities needed to test a meaningful product hypothesis.'],
                    ['question' => 'Can you help before we have detailed specifications?', 'answer' => 'Yes. Discovery sessions can turn an early idea into user journeys, priorities, a delivery plan, and a practical first release.'],
                    ['question' => 'Will the MVP be able to grow later?', 'answer' => 'Yes. We make intentional architectural choices so successful MVPs can evolve without treating the first release as throwaway work.'],
                    ['question' => 'Can you support us after launch?', 'answer' => 'Yes. We can continue with enhancements, infrastructure, security, analytics, integrations, and product iterations as your needs evolve.'],
                ],
                'faq_cta_heading' => 'Ready to Turn Your Idea Into Useful Momentum?',
                'faq_cta_text' => 'Build a focused product foundation that helps you learn, launch, and grow with confidence.',
                'cta_heading' => 'Let Us Help You Build What Your Startup Needs Next',
                'cta_subtitle' => 'Move from concept to a dependable product with a technology partner invested in practical progress.',
            ],
            'travel-tourism' => [
                'short_description' => 'Travel technology that connects discovery, booking, itineraries, operations, and guest experiences.',
                'seo_title' => 'Travel and Tourism Technology Solutions | Tectignis',
                'seo_description' => 'Create better travel booking, itinerary, operations, and guest experiences with connected technology solutions from Tectignis.',
                'seo_keywords' => 'travel technology, travel booking engine, tourism software, itinerary platform, travel portal development',
                'eyebrow' => 'TRAVEL AND TOURISM TECHNOLOGY SOLUTIONS',
                'heading' => 'Inspiring Journeys. Better Connected Travel Operations.',
                'highlight' => 'Better Connected Travel Operations.',
                'intro' => 'Make it easier for travelers to discover, book, and enjoy every experience while giving your team a clearer view of reservations, partners, and service.',
                'features' => ['Simplify booking journeys', 'Coordinate travel operations', 'Personalize guest experiences', 'Grow direct relationships'],
                'badges' => ['Booking Technology', 'Itinerary Management', 'Travel Portals', 'Guest Engagement'],
                'challenge_heading' => 'Many Touchpoints. One Traveler Experience.',
                'challenge_intro' => 'Travel businesses must coordinate destinations, suppliers, reservations, and support while travelers expect fast, personal, always-available service.',
                'challenges' => ['Fragmented booking and supplier information', 'Manual itinerary and document preparation', 'Limited visibility into reservations and fulfillment', 'Inconsistent traveler communication before and during trips', 'Complex partner and inventory coordination', 'Pressure to deliver a seamless mobile-first experience'],
                'solution_heading' => 'Digital Experiences Built Around Better Journeys',
                'solutions' => [
                    ['title' => 'Travel Booking Platforms', 'description' => 'Create clear, responsive booking journeys for packages, services, and experiences.'],
                    ['title' => 'Itinerary Management Systems', 'description' => 'Organize bookings, schedules, documents, travelers, and service details in one place.'],
                    ['title' => 'Travel and Tourism Portals', 'description' => 'Help travelers discover destinations, plans, resources, and local experiences more easily.'],
                    ['title' => 'Supplier and Partner Workflows', 'description' => 'Coordinate availability, confirmations, documents, and communication with partners.'],
                    ['title' => 'Traveler Communication', 'description' => 'Keep guests informed with timely updates, reminders, documents, and support options.'],
                    ['title' => 'Travel Operations Analytics', 'description' => 'Understand bookings, demand, sources, fulfillment, and traveler trends clearly.'],
                ],
                'stats' => [['value' => 'Seamless', 'label' => 'Booking Experiences'], ['value' => 'One View', 'label' => 'Of Trips and Travelers'], ['value' => 'Faster', 'label' => 'Itinerary Workflows'], ['value' => 'Better', 'label' => 'Guest Communication'], ['value' => 'Clearer', 'label' => 'Partner Coordination'], ['value' => 'Scalable', 'label' => 'Travel Growth']],
                'grid' => ['Travel Booking Engines', 'Itinerary Management', 'Travel Portals', 'Package Management', 'Supplier Workflows', 'Traveler Communication', 'Mobile Experiences', 'Travel Analytics'],
                'faqs' => [
                    ['question' => 'Can you build a booking experience around our travel offerings?', 'answer' => 'Yes. We design journeys around your packages, destinations, inventory, traveler needs, and sales process.'],
                    ['question' => 'Can the system help create and manage itineraries?', 'answer' => 'Yes. Itinerary tools can organize bookings, schedules, documents, traveler details, updates, and operational tasks.'],
                    ['question' => 'Can travelers access trip information online?', 'answer' => 'Yes. A traveler portal can provide timely access to plans, documents, updates, support, and relevant recommendations.'],
                    ['question' => 'Can travel operations integrate with other systems?', 'answer' => 'Yes. We assess available supplier, payment, CRM, and operational integrations to create the right connected workflow.'],
                ],
                'faq_cta_heading' => 'Ready to Create Better Connected Travel Experiences?',
                'faq_cta_text' => 'Bring the discovery, booking, and service journey into a more dependable digital experience.',
                'cta_heading' => 'Make Every Journey Easier to Plan, Book, and Enjoy',
                'cta_subtitle' => 'Build travel technology that keeps your travelers and operations moving in the same direction.',
            ],
        ];
    }

    /**
     * @param  array<string, mixed>  $profile
     * @return array<string, mixed>
     */
    private function buildContent(array $profile): array
    {
        return [
            'hero' => [
                'eyebrow' => $profile['eyebrow'],
                'heading' => $profile['heading'],
                'highlight' => $profile['highlight'],
                'intro' => $profile['intro'],
                'cta_primary_label' => 'Talk to an Expert',
                'cta_secondary_label' => 'Explore Solutions',
                'features' => $this->labelItems($profile['features']),
                'badges' => $this->labelItems($profile['badges']),
            ],
            'trust' => ['enabled' => true],
            'challenges' => [
                'enabled' => true,
                'eyebrow' => 'CHALLENGES',
                'heading' => $profile['challenge_heading'],
                'subtitle' => $profile['challenge_intro'],
                'items' => $profile['challenges'],
            ],
            'solutions' => [
                'enabled' => true,
                'eyebrow' => 'HOW WE HELP',
                'heading' => $profile['solution_heading'],
                'cards' => $this->iconItems($profile['solutions']),
            ],
            'stats' => [
                'enabled' => true,
                'subtitle' => 'WHAT BETTER LOOKS LIKE',
                'heading' => 'Built for More Confident Operations',
                'items' => $this->iconItems($profile['stats']),
            ],
            'case_studies' => [
                'enabled' => true,
                'subtitle' => 'SUCCESS STORIES',
                'heading' => 'Real Results. Real Impact.',
            ],
            'solutions_grid' => [
                'enabled' => true,
                'subtitle' => 'WHAT WE OFFER',
                'heading' => 'Solutions We Offer',
                'items' => $this->labelItems($profile['grid']),
            ],
            'faq' => [
                'enabled' => true,
                'subtitle' => 'FAQS',
                'heading' => 'Frequently Asked Questions',
                'items' => $profile['faqs'],
                'cta_heading' => $profile['faq_cta_heading'],
                'cta_text' => $profile['faq_cta_text'],
                'cta_label' => 'Get Started Today',
            ],
            'cta_band' => [
                'enabled' => true,
                'heading' => $profile['cta_heading'],
                'subtitle' => $profile['cta_subtitle'],
                'button_primary_label' => 'Talk to an Expert',
                'button_secondary_label' => 'Request a Consultation',
            ],
        ];
    }

    /**
     * @param  array<int, string>  $labels
     * @return array<int, array{icon: string, label: string}>
     */
    private function labelItems(array $labels): array
    {
        return array_map(
            fn (string $label): array => ['icon' => '', 'label' => $label],
            $labels,
        );
    }

    /**
     * @param  array<int, array<string, string>>  $items
     * @return array<int, array<string, string>>
     */
    private function iconItems(array $items): array
    {
        return array_map(
            fn (array $item): array => ['icon' => '', ...$item],
            $items,
        );
    }

    /**
     * @return array<string, mixed>
     */
    private function genericProfile(string $name, ?string $shortDescription): array
    {
        $description = $shortDescription ?: "Practical technology and support that help {$name} organizations operate with greater clarity and confidence.";

        return [
            'short_description' => $description,
            'seo_title' => "{$name} Technology Solutions | Tectignis",
            'seo_description' => $description,
            'seo_keywords' => strtolower("{$name} technology solutions, digital transformation, business software, IT services"),
            'eyebrow' => strtoupper("{$name} TECHNOLOGY SOLUTIONS"),
            'heading' => "Smarter Technology for {$name} Organizations.",
            'highlight' => "{$name} Organizations.",
            'intro' => "Build connected, secure systems that help your {$name} teams deliver better experiences and stronger operations.",
            'features' => ['Improve operational visibility', 'Connect everyday workflows', 'Protect critical information', 'Scale with confidence'],
            'badges' => ['Connected Operations', 'Secure Technology', 'Practical Automation', 'Expert Support'],
            'challenge_heading' => 'Complex Demands. More Confident Operations.',
            'challenge_intro' => "{$name} organizations need practical technology that helps people work together, respond faster, and make better decisions.",
            'challenges' => ['Disconnected tools and manual handoffs', 'Limited operational visibility', 'Changing customer and stakeholder expectations', 'Growing data security requirements', 'Inefficient reporting and approvals', 'Technology that is difficult to scale'],
            'solution_heading' => "Technology Designed for {$name} Teams",
            'solutions' => [
                ['title' => 'Business Applications', 'description' => 'Build the tools your teams need to manage daily work more effectively.'],
                ['title' => 'Workflow Automation', 'description' => 'Reduce repetitive tasks with clearer, more reliable digital processes.'],
                ['title' => 'Customer and User Portals', 'description' => 'Create straightforward self-service experiences for the people you serve.'],
                ['title' => 'Data and Reporting', 'description' => 'Turn operational information into useful, timely decisions.'],
                ['title' => 'Cybersecurity and Infrastructure', 'description' => 'Protect the systems and information that keep your organization moving.'],
                ['title' => 'Technology Consulting', 'description' => 'Make practical choices about what to improve now and how to grow later.'],
            ],
            'stats' => [['value' => 'Connected', 'label' => 'Everyday Workflows'], ['value' => 'Clearer', 'label' => 'Operational Insight'], ['value' => 'Secure', 'label' => 'Critical Information'], ['value' => 'Faster', 'label' => 'Team Coordination'], ['value' => 'Better', 'label' => 'User Experiences'], ['value' => 'Scalable', 'label' => 'Technology Foundations']],
            'grid' => ['Business Applications', 'Workflow Automation', 'Customer Portals', 'Data and Reporting', 'Cloud Solutions', 'Cybersecurity', 'IT Infrastructure', 'Ongoing Support'],
            'faqs' => [
                ['question' => 'Can you work with our existing systems?', 'answer' => 'Yes. We assess your current tools, data, and workflows before recommending a practical improvement path.'],
                ['question' => 'Can the solution be introduced in phases?', 'answer' => 'Yes. We can prioritize the capabilities that deliver the most immediate value and expand from there.'],
                ['question' => 'How do you keep information secure?', 'answer' => 'We apply appropriate access controls, secure infrastructure, backups, monitoring, and governance practices to the solution scope.'],
                ['question' => 'Can you support the solution after launch?', 'answer' => 'Yes. We can provide support, enhancements, monitoring, and guidance as your needs evolve.'],
            ],
            'faq_cta_heading' => "Ready to Improve Your {$name} Operations?",
            'faq_cta_text' => "Build a clearer, more connected technology foundation for your {$name} organization.",
            'cta_heading' => "Create a Stronger Digital Foundation for {$name}",
            'cta_subtitle' => 'Talk with our experts about practical technology that moves your organization forward.',
        ];
    }
}
